version: 2.1

orbs:
  ecspresso: fujiwara/ecspresso@2.0.4

jobs:
  update_notification_ecs_task:
    docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - ecspresso/install:
          version: v2.8.5
          os: linux
          arch: amd64
      # TODO: OIDC認証を入れる
      - run:
          command: |
            ecspresso version

workflows:
  update-ecs-task:
    jobs:
      - update_notification_ecs_task
